// app state
export const APP_LOADING = 'APP_LOADING';
export const APP_LOADED = 'APP_LOADED';
export const APP_FAILED = 'APP_FAILED';
export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';

// responsive
export const GET_DEVICE = 'GET_DEVICE';
export const GOT_DEVICE = 'GOT_DEVICE';

// sign in
export const SIGNIN_PAGE_LOADING = 'SIGNIN_PAGE_LOADING';
export const SIGNIN_PAGE_LOADED = 'SIGNIN_PAGE_LOADED';
export const SIGNIN_PAGE_FAILED = 'SIGNIN_PAGE_FAILED';
export const SAVE_UID = 'SAVE_UID';
export const SAVE_USER_PROFILE = 'SAVE_USER_PROFILE';
export const USER_SIGNED_IN = 'USER_SIGNED_IN';
export const USER_SIGNED_OUT = 'USER_SIGNED_OUT';

// sign up
export const SIGNUP_PAGE_LOADING = 'SIGNUP_PAGE_LOADING';
export const SIGNUP_PAGE_LOADED = 'SIGNUP_PAGE_LOADED';
export const SIGNUP_PAGE_FAILED = 'SIGNUP_PAGE_FAILED';
export const IS_ADMIN = 'IS_ADMIN';

// home page
export const HOME_PAGE_LOADING = 'HOME_PAGE_LOADING';
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_FAILED = 'HOME_PAGE_FAILED';

// prismic API
export const PRISMIC_API_REQ = 'PRISMIC_API_REQ';
export const PRISMIC_API_SUCCESS = 'PRISMIC_API_SUCCESS';
export const PRISMIC_API_FAIL = 'PRISMIC_API_FAIL';
export const FETCH_TPR_STORY = 'FETCH_TPR_STORY';
export const FETCH_TPR_SUCCESS = 'FETCH_TPR_SUCCESS';
export const FETCH_TPR_FAIL = 'FETCH_TPR_FAIL';

// news API
export const NEWS_CONTAINER_LOADING = 'NEWS_CONTAINER_LOADING';
export const NEWS_CONTAINER_LOADED = 'NEWS_CONTAINER_LOADED';
export const NEWS_API_REQ = 'NEWS_API_REQ';
export const NEWS_API_SUCCESS = 'NEWS_API_SUCCESS';
export const NEWS_API_FAIL = 'NEWS_API_FAIL';

// chat
export const CHAT_PAGE_LOADING = 'CHAT_PAGE_LOADING';
export const CHAT_PAGE_LOADED = 'CHAT_PAGE_LOADED';
export const CHAT_PAGE_FAILED = 'CHAT_PAGE_FAILED';


// acts
export const ACTS_PAGE_LOADING = 'ACTS_PAGE_LOADING';
export const ACTS_PAGE_LOADED = 'ACTS_PAGE_LOADED';
export const ACTS_PAGE_FAILED = 'ACTS_PAGE_FAILED';

// act
export const ACT_PAGE_LOADING = 'ACT_PAGE_LOADING';
export const ACT_PAGE_LOADED = 'ACT_PAGE_LOADED';
export const ACT_PAGE_FAILED = 'ACT_PAGE_FAILED';
export const FETCH_ACT_PROFILE = 'FETCH_ACT_PROFILE';
export const GOT_ACT_PROFILE = 'GOT_ACT_PROFILE';

// gigs
export const GIGS_PAGE_LOADING = 'GIGS_PAGE_LOADING';
export const GIGS_PAGE_LOADED = 'GIGS_PAGE_LOADED';
export const GIGS_PAGE_FAILED = 'GIGS_PAGE_FAILED';
export const FETCH_GIGS_REQ = 'FETCH_GIGS_REQ';
export const FETCH_GIGS_RESP = 'FETCH_GIGS_RESP';
export const RESET_GIGS = 'RESET_GIGS';
export const FETCH_FILTERS = 'FETCH_FILTERS';
export const GIGS_FILTERED = 'GIGS_FILTERED';
export const SELECTED_GIG = 'SELECTED_GIG';
export const FETCH_GIGS_TONIGHT = 'FETCH_GIGS_TONIGHT';
export const GIGS_TONIGHT_RESP = 'GIGS_TONIGHT_RESP';

// me
export const ME_PAGE_LOADING = 'ME_PAGE_LOADING';
export const ME_PAGE_LOADED = 'ME_PAGE_LOADED';
export const ME_PAGE_FAILED = 'ME_PAGE_FAILED';

// filters
export const LOAD_FILTERS = 'LOAD_FILTERS';
export const LOADED_FILTERS = 'LOADED_FILTERS';
export const FILTERS_CHANGED = 'FILTERS_CHANGED';

// news page
export const NEWS_PAGE_LOADING = 'NEWS_PAGE_LOADING';
export const NEWS_PAGE_LOADED = 'NEWS_PAGE_LOADED';
export const NEWS_PAGE_FAILED = 'NEWS_PAGE_FAILED';
export const FETCH_NEWS_REQ = 'FETCH_NEWS_REQ';
export const FETCH_NEWS_RES = 'FETCH_NEWS_RES';

export const ADDDING_USER_TO_GIG = 'ADDDING_USER_TO_GIG';
export const ADDDING_USER_TO_GIG_REQ = 'ADDDING_USER_TO_GIG_REQ';
export const ADDDING_USER_TO_GIG_RES = 'ADDDING_USER_TO_GIG_RES';

//