// app state
export const APP_LOADING = 'APP_LOADING';
export const APP_LOADED = 'APP_LOADED';
export const APP_FAILED = 'APP_FAILED';

// sign in
export const SIGNIN_PAGE_LOADING = 'SIGNIN_PAGE_LOADING';
export const SIGNIN_PAGE_LOADED = 'SIGNIN_PAGE_LOADED';
export const SIGNIN_PAGE_FAILED = 'SIGNIN_PAGE_FAILED';
export const SAVE_UID = 'SAVE_UID';

// sign up
export const SIGNUP_PAGE_LOADING = 'SIGNUP_PAGE_LOADING';
export const SIGNUP_PAGE_LOADED = 'SIGNUP_PAGE_LOADED';
export const SIGNUP_PAGE_FAILED = 'SIGNUP_PAGE_FAILED';


// home page
export const HOME_PAGE_LOADING = 'HOME_PAGE_LOADING';
export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_FAILED = 'HOME_PAGE_FAILED';

// gigs
export const GIGS_PAGE_LOADING = 'GIGS_PAGE_LOADING';
export const GIGS_PAGE_LOADED = 'GIGS_PAGE_LOADED';
export const GIGS_PAGE_FAILED = 'GIGS_PAGE_FAILED';
export const FETCH_GIGS_REQ = 'FETCH_GIGS_REQ';
export const FETCH_GIGS_RESP = 'FETCH_GIGS_RESP';
export const RESET_GIGS = 'RESET_GIGS';
export const FETCH_FILTERS = 'FETCH_FILTERS';
export const GIGS_FILTERED = 'GIGS_FILTERED';
export const SELECTED_GIG = 'SELECTED_GIG';

// filters
export const LOAD_FILTERS = 'LOAD_FILTERS';
export const LOADED_FILTERS = 'LOADED_FILTERS';
export const FILTERS_CHANGED = 'FILTERS_CHANGED';

// blog
export const NEWS_PAGE_LOADING = 'NEWS_PAGE_LOADING';
export const NEWS_PAGE_LOADED = 'NEWS_PAGE_LOADED';
export const NEWS_PAGE_FAILED = 'NEWS_PAGE_FAILED';
export const FETCH_NEWS_REQ = 'FETCH_NEWS_REQ';
export const FETCH_NEWS_RES = 'FETCH_NEWS_RES';